import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // // // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [{ type: "autogenerated", dirName: "." }],


  mySidebar: [
    {
      type: 'doc',
      id: 'intro', // document ID
      label: 'Latest Releases', // sidebar label
    },
    {
      type: 'doc',
      id: 'intro', // document ID
      label: 'Compiler', // sidebar label
    },
    {
      type: 'doc',
      id: 'intro', // document ID
      label: 'Examples', // sidebar label
    },
    {
      type: 'doc',
      id: 'intro', // document ID
      label: 'VSCode Extension', // sidebar label
    },
    {
      type: 'doc',
      id: 'intro', // document ID
      label: 'Wallet', // sidebar label
    },
  ],
};

export default sidebars;
